name: Create release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release-zips:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Find LabVIEW directories and create zips
      id: create_zips
      run: |
        for dir in LabVIEW_*; do
          if [ -d "$dir" ]; then
            zip -r "${dir}.zip" "$dir"
          fi
        done

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: '*.zip'
        asset_name: ${{ github.ref }}-zips
        asset_content_type: application/zip
